version: '2'

services:
  mysql:
    image: mysql
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Novaword123
      - MYSQL_DATABASE=novaword
      - TZ=Asia/Shanghai
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
  novaword:
    image: registry.cn-hangzhou.aliyuncs.com/trentzhou/novaword
    volumes:
      - ./upload:/upload
      - ./static:/static
    ports:
      - 8000:8000
    links:
      - mysql
    restart: always
    environment: &common_env
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE_NAME=novaword
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=Novaword123
      - DJANGO_MANAGEPY_MIGRATE=on
      - STARTUP_DELAY=30
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
      - ADMIN_EMAIL=quan@zhouyequan.com
      - EMAIL_HOST=smtp.novaword.cn
      - EMAIL_PORT=465
      - EMAIL_HOST_USER=mailer@novaword.cn
      - EMAIL_HOST_PASSWORD=Novaword123
      - EMAIL_FROM="mailer@novaword.cn"
      - REDIS_HOST=redis
      - DJANGO_MANAGEPY_COLLECTSTATIC=on
  redis:
    image: redis
  celery:
    image: registry.cn-hangzhou.aliyuncs.com/trentzhou/novaword
    volumes:
      - ./upload:/upload
    command: celery
    links:
      - mysql
      - redis
    restart: always
    environment: *common_env
  beat:
    image: registry.cn-hangzhou.aliyuncs.com/trentzhou/novaword
    volumes:
      - ./upload:/upload
    command: beat
    links:
      - mysql
      - redis
    restart: always
    environment: *common_env
